# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
# default: &default
#   adapter: sqlite3
#   pool: 5
#   timeout: 5000

# development:
#   <<: *default
#   database: db/development.sqlite3

default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: pim
  username: postgres
  password: password
  schema_search_path: "pim"
  

dev:  
  <<: *default
  host: 172.168.0.61
  database: pim
  username: <%= ENV["PIM_DATABASE_USERNAME"] %>
  password: <%= ENV["PIM_DATABASE_PASSWORD"] %>  
  schema_search_path: "pim"
  port: 9999

satging:  
  <<: *default  
  database: pim
  username: <%= ENV["PIM_DATABASE_USERNAME"] %>
  password: <%= ENV["PIM_DATABASE_PASSWORD"] %>  
  schema_search_path: "pim"

development:  
  <<: *default  
  database: pim
  username: <%= ENV["PIM_DATABASE_USERNAME"] %>
  password: <%= ENV["PIM_DATABASE_PASSWORD"] %>  
  schema_search_path: "pim"

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
# test:
#   <<: *default
#   database: db/test.sqlite3

# production:
#   <<: *default
#   database: db/production.sqlite3
